name = "feh"
version = "1.0.2"
license = "MIT"
author = "Sam Harrison"
maintainer = "samharrison.xg@gmail.com"

[[ example ]]
name = "example"
source-dir = "example"
main = "example_usage.f90"

[[ test ]]
name = "tests"
source-dir = "tests"
main = "run_tests.f90"

[install]
library = true